version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-data1:/data

  node-red2:
      image: nodered/node-red:latest
      environment:
        - TZ=Europe/Amsterdam
      ports:
        - "1881:1880"
      networks:
        - node-red-net
      volumes:
        - node-red-data2:/data      

volumes:
  node-red-data1:
  node-red-data2:

networks:
  node-red-net: